server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DocG
    username: postgres
    password: 'Deeksha@001'

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen3:1.7b
      temperature: 0.2
      timeout: PT3M